### ISSUE TITLE
No start script

### ISSUE THREAD

**Issue by mjhough** [learn-co-curriculum/react-actions-lab#13]
Any chance the missing start script could be fixed on all the labs in this section? @sgharms

**Comment by sgharms** [comment]
@mjhough Can you give me some context about how you're using this script? Are you using it to kick up a persistent server during your development cycle?

**Comment by sgharms** [comment]
(Oh, and yes, something like `start` should be in place....but there may be an _even_ better option).

**Comment by mjhough** [comment]
@sgharms In the labs earlier we were instructed to run `npm start` in order to start the server and display the react app. In these labs all I get is an error saying that the start script is missing (which is true).

I'd be happy for a better option, it's just that I haven't learned anything about the behind the scenes of react and don't have a way of seeing what I am doing in the browser.

**Comment by sgharms** [comment]
Cool. Let me work with the code a bit and update shortly.

**Comment by sgharms** [comment]
@mjhough I'm getting my team together to sort out a fix on this. We've tried to piecemeal fix this and I want to come up with a better strategy. We're going to try to fix the 3 you reported tomorrow morning and then we'll figure out how to generalize the solution.

In the short term, `npm start` can be re-added by adding a `   "start": "react-scripts start",` under the "scripts" object in `package.json`.

**Comment by mjhough** [comment]
@sgharms Unfortunately, adding `react-scripts start` doesn't work. It requires files in certain directories and then when that is done I get import order errors.

**Comment by sgharms** [comment]
Shucks. OK, we'll have this improved tomorrow.

**Comment by mjhough** [comment]
Thanks

**Comment by DanielSeehausen** [comment]
Hi @mjhough:

The three labs:

react-changing-state-lab
react-stores-lab
react-actions-lab

Have had their dependencies updated and should be working well. 
With these labs, there is a slightly different flow that you should be able to use.

After cloning, `npm install` per usual
You can then run the tests by executing `npm run test` and you will get your favorite Nyan Cat print out
Additionally, if you would like to bundle your react app, `npm run bundle` will do that for you and you are free to inspect in the browser however you like!

This should be working for both node v6 as well as node v9 (you can run `node -v` to see which version you have). I would recommend installing and using v9 for these only because I am sure it is working under that major (i.e. the current up-to-date) version!

If you are having any problems with this, please @danielseehausen me here and we can set up a screen share to see exactly what the problem is!

**Comment by mjhough** [comment]
@DanielSeehausen Thanks. Unfortunately the other labs in this section also have the same issues as these labs were having. Here are the two repos:
https://github.com/learn-co-students/react-unidirectional-data-lab-cb-000
https://github.com/learn-co-students/react-type-ahead-wikipedia-search-lab-cb-000

I told Cailee this, but the message mustn't have been passed on.

**Comment by sgharms** [comment]
She did pass it on, we've only attacked the first 3 first.

**Comment by mjhough** [comment]
Ok great. Thank you for your help so far.

**Comment by mjhough** [comment]
Just to clarify, to see my work in the browser, I should run `npm run bundle` and then open `index.html` in my browser?

**Comment by sgharms** [comment]
@mjhough @DanielSeehausen has reported that issues around react-unidirectional... and react-type-ahead...have been fixed.

**Comment by zbianca** [comment]
I tried many things, including what has been described here. It seems like dependencies are crashing again.
